Mergear UEAST-CRUD a master
Nannajpg/IDS-admin-panel pull request #7
Opened 2022-12-12 03:24 UTC by luizzzito

Lo que contiene:
CRUDS de:
-Usuarios
-Eventos
-Anuncios
-Cromos
-Equipos

Lo que le falta:
-Paginacion en anuncios, cromos y equipos.
-Selects relacionales.
-Gestion de errores con modals.
-Correcion de detalles de front.

2022-12-12 12:38 UTC, Hector1567XD commented
Rama terrorista

2022-12-14 00:20 UTC, HopeAero commented
No estoy asignado pero tengo fe que esto se mergeara pronto para yo hacerle deploy

2022-12-14 01:18 UTC, Hector1567XD commented
> No estoy asignado pero tengo fe que esto se mergeara pronto para yo hacerle deploy

Aunque no se mergee le puedes hacer deploy en staging amigo @HopeAero

2022-12-14 01:20 UTC, Yisustxz approved these changes

2022-12-14 10:24 UTC, AureumBox commented on src/app/store.js
> +}) */
Si no se va a usar, debería borrarse

2022-12-14 10:24 UTC, AureumBox commented on src/cores/events/Pagination.jsx
> +const Pagination = ({ postsPerPage }) => {
Quizas separar esto de la carpeta events y ponerlo en components, porque se repite en events y users

2022-12-14 10:24 UTC, AureumBox commented on src/features/stickers/stickerSlice.js
> +        prevPage: (state, action) => {
prevPage y next Page al final no se están usando

2022-12-14 10:24 UTC, AureumBox commented on src/services/team.services.js
> +export const fetchTeams = async (page = 0, eventid = '', teamname = '') => {
Agregar try catch

2022-12-14 23:31 UTC, Hector1567XD reviewed
Feedback Parte 1

2022-12-14 23:31 UTC, Hector1567XD commented on src/components/useForm.jsx
> +const useForm = () => {
Esto no es un componente 🤔 , es un hook, recomendaria un `src/hooks/use-form.js`

2022-12-14 23:31 UTC, Hector1567XD commented on src/cores/ads/Ad.jsx
> +  const ad = useSelector((state) => state.ads.ads.find((ad) => ad.id === id));
Podrian crear un selector en algun otro archivo e importarlo aqui, recomiendo tambien usar re-select de redux-toolkit

```suggestion
  const ad = useSelector(selectAdById(id));
```

(Esto es mega-opcional, pero ayuda a mejorar la legibilidad del codigo)

2022-12-14 23:31 UTC, Hector1567XD commented on src/cores/auth/ErrorMessage.jsx
> +export default ErrorMessage */
xd?

2022-12-14 23:31 UTC, Hector1567XD commented on src/cores/auth/Login.jsx
> +            /* autoComplete="off" */
```suggestion
```

2022-12-14 23:31 UTC, Hector1567XD commented on src/cores/auth/useLoginForm.jsx
> +      alert(e)
```suggestion
      alert(e)
```

Las alertas son super feas, lo mejor seria que hiciesen un modal dedicado a mostrar las alertas de error o mostraran un toastr

2022-12-14 23:31 UTC, Hector1567XD commented on src/cores/dashboard/Menu.jsx
> +
```suggestion
```

2022-12-14 23:31 UTC, Hector1567XD commented on src/cores/dashboard/Menu.jsx
> +
```suggestion
```

2022-12-14 23:31 UTC, Hector1567XD commented on src/cores/dashboard/Menu.jsx
> +
```suggestion
```

2022-12-14 23:31 UTC, Hector1567XD commented on src/cores/events/CreateForm.jsx
> +      return data;
```suggestion
      return await eventsServices.createEvent(event);
```

2022-12-14 23:31 UTC, Hector1567XD commented on src/cores/events/CreateForm.jsx
> +      return data;
Entiendo que "event" viene de un estado, al hacer cosas como `event.status = XXXX`, se esta produciendo una mutacion de estado por un medio que no es "setState" de React!, esto puede ocasionar fallos en un futuro, recomiendo copiar el objeto

```suggestion
  const create = async (event) => {
    try {
      const eventData = { ...event };
      if (event.status === "Activo"){
        eventData.status = true;
      } else {
        eventData.status = false;
      }

      const data = await eventsServices.createEvent(eventData);
      return data;
```

O incluso mas directo...

```suggestion
  const create = async (event) => {
    try {
      return await eventsServices.createEvent({
        ...event,
        status: (event.status === 'Activo')
      });
```

2022-12-14 23:31 UTC, Hector1567XD commented on src/cores/events/EventsList.jsx
> +    const amount = useSelector(state => state.events.amount)
```suggestion
    const { page, events, amount } = useSelector(({ events: { page, events, amount } }) => ({ page, events, amount }));
```

2022-12-14 23:31 UTC, Hector1567XD commented on src/cores/events/EventsList.jsx
> +    }, [dispatch, page, amount])
Vale la pena hacer una funcion siempre que no la uses indiatamente despues de declararla xD, es decir, ¿para que se hizo esto una funcion en primer lugar? (quiza por el await? XDD), mejor invoca todo directamente

```suggestion
    useEffect(async () => {
        dispatch(resetEvents());
        try {
            const data = await eventsServices.fetchEvents(page);
            data.events.forEach(event => {
                dispatch(addEvent(event));
            });
            dispatch(setAmount(data.paginate.total));
        } catch(e) {
            console.log(e);
        }
    }, [dispatch, page, amount])
```

2022-12-14 23:31 UTC, Hector1567XD commented on src/cores/events/EventsList.jsx
> +                {events.map(event => (<Event event={event} key={event.id}/>))}
```suggestion
                {events.map(event => (<Event event={event} key={'event-'+event.id}/>))}
```

2022-12-14 23:31 UTC, Hector1567XD commented on src/cores/events/EventsList.jsx
> +                {events.map(event => (<Event event={event} key={event.id}/>))}
Ese prefijo es para que no choque con otros objetos que tambien necesitan una "key"

2022-12-14 23:32 UTC, Hector1567XD commented on src/cores/events/EventsList.jsx
> +    const amount = useSelector(state => state.events.amount)
O quizas hasta mejor...
```suggestion
    const { page, events, amount } = useSelector(state => state.events);
```

2022-12-27 22:03 UTC, Yisustxz commented on src/cores/auth/useLoginForm.jsx
> +      alert(e)
no

2023-01-03 22:43 UTC, Yisustxz approved these changes

2023-01-04 02:12 UTC, AureumBox approved these changes
Qué lindo está ese PR >.<

A futuro, quizá consideren cambiar la paginación de cromos y stickers, porque ya vi que no es viable xd

Si hay 20 páginas, será incómodo. Pero shh. Quizá no lo necesitemos gracias a las tablas.

El CRUD de equipos navega una página de más, una página vacía porque está ahí de extra xd.

Pero funcionalmente está bien. Aprobado para master ig

2023-01-04 02:56 UTC, Hector1567XD requested changes
Parte 2

2023-01-04 02:56 UTC, Hector1567XD commented on package.json
> +    "react-toastify": "^9.1.1",
Tienen los `toast` instalados y no los usan e.e... pero bueno, anoten esto como una mejora para despues, creenle una tarea en notion

2023-01-04 02:56 UTC, Hector1567XD commented on src/config.js
> +export const API_URL = process.env.REACT_APP_APIURL
```suggestion
export const API_URL = process.env.REACT_APP_API_URL
```
Maybe?

2023-01-04 02:56 UTC, Hector1567XD commented on src/cores/ads/EditForm.jsx
> +    dispatch(editAd())
Ese editAd() no recibe ningun parametro 🤔 ?

2023-01-04 02:56 UTC, Hector1567XD commented on src/cores/ads/Form.jsx
> +        await action(ad, id);
```suggestion
        await onSubmit(ad, id);
```

Recomiendo el cambio de nombre como si fuese un evento

2023-01-04 02:56 UTC, Hector1567XD commented on src/cores/ads/ModalDeleteAd.jsx
> +      dispatch(deleteAd());
deleteAd no recibe ningun parametro 🤔 ?

2023-01-04 02:56 UTC, Hector1567XD commented on src/cores/auth/Login.jsx
> +
Wtf o.o?

No sabia que podian hacer esto en forma declarada pero... bueno, la idea es que el login sea un mecanismo hyprativo, como todo lo demas, le das clic a algo y el llama a un servicio u orgnaizacion

2023-01-04 02:56 UTC, Hector1567XD commented on src/cores/auth/useLoginForm.jsx
> +      alert(e)
Usen toastr son bien sencillos de usar

2023-01-04 02:56 UTC, Hector1567XD commented on src/cores/events/EditForm.jsx
> +
```suggestion
      const eventData = {
          ...event,
          status: !!(event.status === "Activo")
      }
      await eventsServices.editEvent(userToken, eventData, id);
      dispatch(editEvent(eventData));

```
Asi evitamos modificar el objeto original que te trae los datos

2023-01-04 02:56 UTC, Hector1567XD commented on src/cores/events/EditForm.jsx
> +      }
Creo que esto deberria estar dentro del servicio 🤔... y al final nosotros solo hacemos `alert(error);`

2023-01-04 02:56 UTC, Hector1567XD commented on src/cores/events/EditForm.jsx
> +  }, [id, events]);
Contexto?, por que debe encontrarlo en la store local para funcionar 🤔?

2023-01-04 02:56 UTC, Hector1567XD commented on src/cores/events/EditForm.jsx
> +  }, [id, events]);
Que pasa si... es un evento que efectivamente existe pero esta en una pagina diferente a la actual?

2023-01-04 02:56 UTC, Hector1567XD commented on src/cores/events/EditForm.jsx
> +  }, [id, events]);
O... esto viene de un eventsAll que nos traera TODOS los eventos ?

2023-01-04 02:56 UTC, Hector1567XD commented on src/cores/events/Event.jsx
> +        console.log(e);
Su Alert o toast mostrando un error!

2023-01-04 02:56 UTC, Hector1567XD commented on src/cores/stickers/StickerCard.js
> +            const stickerToDelete = stickers.find(sticker => sticker.id == id)
¿Cual es la necesidad de encontrarlo dentro de la store si ya tengo el ID?, no es necesariamente algo malo pero me llama la atencion

2023-01-04 02:56 UTC, Hector1567XD commented on src/cores/stickers/StickerForm.js
> +    }));
Resumanlo, creen un hook, incluso este hook podria reutilizarse en otros muchisimos sitios
```suggestion
    const eventsOptions = useEventsOptions();
```

Hook en cuestion:
```
function useEventsOptions() {
    const events = useSelector(state => state.events.eventsAll);
    return events.map((event) => ({
        id: event.id,
        name: event.eventName,
    }))
}
```

2023-01-04 02:56 UTC, Hector1567XD commented on src/cores/stickers/StickerForm.js
> +    }));
```suggestion
    const teamsOptions = useTeamsOptions();
```
Lo mismo que con events, un hook personalizado, AUNQUE en este caso... "events" dice "eventsAll" asumo son todos los eventos

Pero "teams" realmente son TODOS los teams 👀 ??, se me hace a que estan sacandolo del lugar de la store que deberia PAGINAR teams, no de donde se almacenen todos los teams, sugeriria hacer un "teamsAll".

2023-01-04 02:56 UTC, Hector1567XD commented on src/cores/stickers/StickerForm.js
> +                // Mostrar un error
```suggestion
                // Si porfavor, mostrar un error XD
```

2023-01-04 02:56 UTC, Hector1567XD commented on src/cores/stickers/StickerForm.js
> +            }
No se esta usando el finally, sera extremedamente util para el loading pero no lo han puesto todavia...

2023-01-04 02:56 UTC, Hector1567XD commented on src/cores/stickers/StickerForm.js
> +                // Mostrar un error
```suggestion
                // Muestren el error ps
```

2023-01-04 02:56 UTC, Hector1567XD commented on src/cores/stickers/StickerForm.js
> +    }, []);
```suggestion
    }, [userToken]);
```

2023-01-04 02:56 UTC, Hector1567XD commented on src/cores/stickers/StickerForm.js
> +    }, []);
```suggestion
    }, [userToken]);
```

2023-01-04 02:56 UTC, Hector1567XD commented on src/cores/stickers/StickerForm.js
> +            setSticker(stickers.find(sticker => sticker.id == params.id))
Me preocupa, como funciona esto para cuando es un sticker que esta fuera de la primera pagina?, creo que deberia haber un endpoint especifico en el servicio que pida la informacion del recurso en ese caso

2023-01-04 02:56 UTC, Hector1567XD commented on src/cores/stickers/StickerForm.js
> +                    <option value='Delantero'>Delantero</option>
El backend acepta los valores
"Arquero" "Defensa" "Medioentro" "Delantero" asi en español y con masyusculas ?

2023-01-04 02:56 UTC, Hector1567XD commented on src/services/users.services.js
> +    throw new Error('error creando usuario');
```suggestion
    throw new Error(e.message);
```
Algo asi seria mejor?, tambien me preocupa que NO se este mostrando el error que venga del servidor, es decir el que esta en "response.message"

2023-01-04 02:56 UTC, Hector1567XD commented on src/services/users.services.js
> +    throw new Error('error creando usuario');
Y esta es una correcion no solo para este servicio si no para todos

2023-01-04 02:56 UTC, Hector1567XD commented on src/services/users.services.js
> +    throw new Error('error creando usuario');
Igual si es mucho trabajo me dicen y la podemos dejar para una tarea aparte

2023-01-04 02:56 UTC, Hector1567XD commented on src/services/team.services.js
> +    console.log(error.message)
Lo mismo.... los errores, no se mostraran nunca en el front. hay que hacer mejor uso del catch

2023-01-04 02:56 UTC, Hector1567XD commented on src/services/auth.services.js
> +        throw new Error('Datos incorrectos');
El error NO siempre es por datos incorrectos... hay que buscar forma de distinguir estos errores y enviar el error real que viene del servidor

2023-01-04 02:56 UTC, Hector1567XD commented on src/index.js
> +); */
```suggestion
```

2023-01-04 02:56 UTC, Hector1567XD commented on src/cores/teams/TeamForm.jsx
> +              // Mostrar un error
```suggestion
              // Si porfavor
```

2023-01-04 19:06 UTC, luizzzito commented on package.json
> +    "react-toastify": "^9.1.1",
okka

2023-01-04 19:43 UTC, luizzzito commented on src/cores/auth/useLoginForm.jsx
> +      alert(e)
jamas

2023-01-04 19:53 UTC, luizzzito commented on src/cores/stickers/StickerForm.js
> +            }
NO USAREMOS EL LOADING >:C

2023-01-04 19:54 UTC, luizzzito commented on src/cores/stickers/StickerForm.js
> +                // Mostrar un error
mira, me estas arrechando, ahora por burlon usare un console.dios >:(

2023-01-04 19:56 UTC, luizzzito commented on src/cores/stickers/StickerForm.js
> +                    <option value='Delantero'>Delantero</option>
si, igual eso se cambiara a forward, midfielder, defender, y goalkeeper

2023-01-05 21:18 UTC, Hector1567XD commented on src/cores/ads/EditForm.jsx
> +    dispatch(editAd())
@luizzzito

2023-01-05 21:19 UTC, Hector1567XD commented on src/cores/auth/Login.jsx
> +
@luizzzito

2023-01-06 01:38 UTC, luizzzito commented on src/cores/events/Event.jsx
> +        console.log(e);
Todavia no esta resuelto en el PR, estamos en proceso de implementar los toasts para los errores del try y catch.

2023-01-06 01:39 UTC, luizzzito commented on src/cores/stickers/StickerForm.js
> +                // Mostrar un error
Todavia no esta resuelto en el PR, estamos en proceso de implementar los toasts para los errores del try y catch.

2023-01-06 01:40 UTC, luizzzito commented on src/cores/stickers/StickerForm.js
> +            setSticker(stickers.find(sticker => sticker.id == params.id))
Se comunicará esta corrección al grupo de Backend.

2023-01-06 01:42 UTC, luizzzito commented on src/services/users.services.js
> +    throw new Error('error creando usuario');
Todavia no esta resuelto en el PR, estamos en proceso de implementar los toasts para los errores del try y catch.

2023-01-06 01:42 UTC, luizzzito commented on src/services/team.services.js
> +    console.log(error.message)
Todavia no esta resuelto en el PR, estamos en proceso de implementar los toasts para los errores del try y catch.

2023-01-06 01:42 UTC, luizzzito commented on src/services/auth.services.js
> +        throw new Error('Datos incorrectos');
Todavia no esta resuelto en el PR, estamos en proceso de implementar los toasts para los errores del try y catch.

2023-01-06 01:48 UTC, Hector1567XD requested changes
Avisame cuando esten "resueltos" los comentarios

2023-01-06 01:48 UTC, Hector1567XD commented on src/cores/stickers/StickerCard.js
> +            const stickerToDelete = stickers.find(sticker => sticker.id == id)
?

2023-01-06 01:48 UTC, Hector1567XD commented on src/cores/stickers/StickerForm.js
> +            setSticker(stickers.find(sticker => sticker.id == params.id))
Link de la tarea?

2023-01-06 01:49 UTC, Hector1567XD commented on src/cores/stickers/StickerForm.js
> +                    <option value='Delantero'>Delantero</option>
Cambialo ya en este PR por que ya el backend esta por pasar a produccion ese cambio

2023-01-06 02:13 UTC, luizzzito commented on src/services/team.services.js
> +    console.log(error.message)
https://www.notion.so/Usar-toasts-al-momento-de-mostrar-errores-1fc138843440405fa4261fbbfdfa8e21

2023-01-06 02:52 UTC, luizzzito commented on src/cores/stickers/StickerForm.js
> +            setSticker(stickers.find(sticker => sticker.id == params.id))
https://www.notion.so/Realizar-endpoints-de-obtener-item-por-id-siendo-los-items-ads-users-events-y-stickers-302c280ae4a5488cafa7eb6ddab6193d

2023-01-06 03:40 UTC, Hector1567XD approved these changes

2023-01-06 13:35 UTC, merged